import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BottomNavigation from "./components/BottomNavigation";
import ThemeProviderClient from "./context/ThemeProviderClient";
import { UserProvider } from "./context/UserContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ThemeProviderClient>
          <UserProvider>
            <main className="mt-4 mx-4" style={{ paddingBottom: '70px' }}>
              {children}
            </main>
            <BottomNavigation />
          </UserProvider>
        </ThemeProviderClient>

      </body>
    </html>
  );
}
